language: c
script: ./configure --disable-nls --enable-ssl $CONFIGURE_WITH && make -j $(nproc)
compiler:
  - gcc
  - clang
matrix:
  fast_finish: true
  allow_failures:
    - env: CONFIGURE_WITH="--with-contrib"
env:
  - CONFIGURE_WITH=""
  - CONFIGURE_WITH="--with-perl"
  - CONFIGURE_WITH="--enable-contrib"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y libperl-dev
notifications:
  irc: "irc.devnet.pw#GnuTheme"